services:
  
  api:
    build: ./api
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/data

  fullnodeUpdate:
    build: ./
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/data

